[package]
name = "rational_impl"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[profile.release]
strip = "symbols"
lto = true

[dependencies.rational_impl_types]
path = "../rational_impl_types"

[features]
link_static = []
